### ISSUE TITLE
不开源你抄不到是吗？

### ISSUE THREAD

**Issue by Mythologyli** [ihjycc/RUN#3]
一个静态页面网站有个锤子成本，别人发个 #1 你去 lock，写个 README 都要抄别人的

看看人家库用的什么许可证：https://github.com/libimobiledevice/libimobiledevice

我的建议是不要挣亏心钱，你有本事去支持 ios 17，你这钱收的还稍微有点道理

**Comment by ihjycc** [comment]
你也有手动模式吗，固定的路线随机打卡点怎么用，你的项目排名很高啊，为何需要在我这里发言呢？人们都会选择适合自己的东西，这都是钱不钱的问题吗？🙁
不开源只是防止被步道乐跑官方抓到特征。
相似的产品很多，大家也可以多多关注！

**Comment by ihjycc** [comment]
项目性质特殊，就和你们玩游戏开挂一样，网站上有免费开源的挂，也有付费闭源的挂，能来github相信都有自己的选择识别能力，大家根据自己需求选择就好了，当然也不要去其他人项目底下攻击或者引流，更不要评论谁的好谁的差，因为选择的权利在你们自己手上！

**Comment by Mythologyli** [comment]
> 你也有手动模式吗，固定的路线随机打卡点怎么用

和这有什么关系，我提到过我的项目了吗，何况我是在批评你软件的功能吗

> 你的项目排名很高啊，为何需要在我这里发言呢？

你在说 Github 搜索排名吗？我又不卖钱，我根本不关心这个。我看到你这个 repo 纯粹是因为 Geniucker 告诉我了

> 不开源只是防止被步道乐跑官方抓到特征。

这就有点扯了。你违反许可证闭源的事情先不提，你不开源就代表你要收费吗

**Comment by ihjycc** [comment]
Geniucker的项目哪点和这个相似了呢😐，我记得不是Python脚本，又或者其他语言的实现，我不记得了，您可以动动你宝贵的手指下载下了测试一下😓

每个联系我的用户，我早就开始提供免费的激活码了！

**Comment by ihjycc** [comment]
大部分的更新，我也没有在github上提供，回复您的消息，也只是收到了官方邮件，我也会在后续版本上提到，插件:
https://github.com/libimobiledevice/libimobiledevice
祝好！

**Comment by Mythologyli** [comment]
> Geniucker的项目哪点和这个相似了呢

我看了看 Geniucker 的 repo，人家一开始用的 py 后来才转的 go，该动动动动手去看看的是你吧

话又说回来，我说你和他的相似了吗？明明在说你违反许可证的事情，你用的 https://github.com/doronz88/pymobiledevice3 ，你自己好好看看人家是什么许可证

**Comment by Mythologyli** [comment]
> 每个联系我的用户，我早就开始提供免费的激活码了！

你需要按照 GPL 的要求公开你的源代码

**Comment by ihjycc** [comment]
现在公开源代码是对已经在使用本项目的用户的不负责🤥

**Comment by ADSR1042** [comment]
不公开源代码是对许可证的亵渎

**Comment by ihjycc** [comment]
我并没有使用遵循GPL协议的代码，软件调用的libimobiledevice程序为已经编译过的二进制文件，并不是源代码。请您先下载此项目试用，谢谢！

**Comment by ihjycc** [comment]
请您充分理解GPL协议，项目内容，再做评论，程序内未包括任何遵循GPL协议的代码。您的水军朋友已经浪费了我很多时间，此议题稍后会关闭！

**Comment by ADSR1042** [comment]
如果一个库是 GPL 的，所有用到该库的软件必须也是 GPL。

**Comment by ihjycc** [comment]
我并未使用遵循GPL协议的库，软件调用是.exe文件，再次请你充分理解此协议内容，和项目内容。

**Comment by ADSR1042** [comment]
如果你修改了 GPL 软件，则你的修改，连同所有修改的衍生物，都必须使用 GPL 发布。
exe是衍生物
你没有权力分发这个exe

**Comment by ihjycc** [comment]
.exe文件并不是我修改的，亦或者编译的，https://github.com/libimobiledevice/libimobiledevice已经提供下载，用户自行选择下载，软件内提供下载按钮，你应该还未搞懂，让你朋友来回复我吧！

**Comment by Mythologyli** [comment]
好，你现在既然承认你调用的是exe

那几个exe的源代码都是在gpl下分发的。人家也没有发布编译产物。你说你的编译产物是下载的，我也不知道你是从哪里下载的

你的行为显然打破了gpl的传播，因为你发布的压缩文件里只包含了那几个exe。下载你的压缩文件的人根本认识不到那几个exe是gpl软件，也无法认识到他们对这部分拥有的权利

**Comment by Mythologyli** [comment]
https://github.com/iOSRealRun-cli/iOSRealRun-cli/issues/7

哈哈，有意思的来了，你不是说你的跟人家没关系吗

**Comment by ihjycc** [comment]
😓

**Comment by ihjycc** [comment]
和你交流简直是浪费时间，麻烦直接摆明来意

**Comment by ihjycc** [comment]
我的程序只提供cmd命令对一些插件或者.exe程序的调用，我不觉得需要开源，并且我需要为我的用户负责，也不能开源算法或者任何代码。

**Comment by Mythologyli** [comment]
许可证可不是“你觉得”

**Comment by ihjycc** [comment]
早些时间的Python脚本程序已经停止维护。

**Comment by Mythologyli** [comment]
违反许可证，然后给自己带上一个为用户负责的冠冕堂皇的帽子，啧啧啧

**Comment by ihjycc** [comment]
请不要拿Geniucker的项目继续碰瓷

**Comment by Mythologyli** [comment]
我的来意说的还不够清楚吗，停止违反许可证的行为

**Comment by ihjycc** [comment]
这并没有违反开源协议，请悉知

**Comment by ihjycc** [comment]
后续版本我将从压缩包里删除libimobiledevice，并引导用户自行下载或者提供镜像下载。

**Comment by Mythologyli** [comment]
我根本就没跟你说你违反那个mit的问题
你违反的是gpl，就是你说你调用的那个exe

**Comment by ihjycc** [comment]
谢谢你的提醒，调用方面的代码我会单独开源，也会出一些中文教程。

**Comment by Mythologyli** [comment]
请及时移除侵权的版本/发新版，而非及时把 issue 关掉

**Comment by ihjycc** [comment]
我违反什么许可证了？你是作者吗？
